// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/framework/step_stats.proto

package tensorflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AllocatorMemoryUsed struct {
	AllocatorName string `protobuf:"bytes,1,opt,name=allocator_name,json=allocatorName" json:"allocator_name,omitempty"`
	// These are per-node allocator memory stats.
	TotalBytes int64 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes" json:"total_bytes,omitempty"`
	PeakBytes  int64 `protobuf:"varint,3,opt,name=peak_bytes,json=peakBytes" json:"peak_bytes,omitempty"`
	// The bytes that are not deallocated.
	LiveBytes int64 `protobuf:"varint,4,opt,name=live_bytes,json=liveBytes" json:"live_bytes,omitempty"`
	// These are snapshots of the overall allocator memory stats.
	// The number of live bytes currently allocated by the allocator.
	AllocatorBytesInUse int64 `protobuf:"varint,5,opt,name=allocator_bytes_in_use,json=allocatorBytesInUse" json:"allocator_bytes_in_use,omitempty"`
}

func (m *AllocatorMemoryUsed) Reset()                    { *m = AllocatorMemoryUsed{} }
func (m *AllocatorMemoryUsed) String() string            { return proto.CompactTextString(m) }
func (*AllocatorMemoryUsed) ProtoMessage()               {}
func (*AllocatorMemoryUsed) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{0} }

func (m *AllocatorMemoryUsed) GetAllocatorName() string {
	if m != nil {
		return m.AllocatorName
	}
	return ""
}

func (m *AllocatorMemoryUsed) GetTotalBytes() int64 {
	if m != nil {
		return m.TotalBytes
	}
	return 0
}

func (m *AllocatorMemoryUsed) GetPeakBytes() int64 {
	if m != nil {
		return m.PeakBytes
	}
	return 0
}

func (m *AllocatorMemoryUsed) GetLiveBytes() int64 {
	if m != nil {
		return m.LiveBytes
	}
	return 0
}

func (m *AllocatorMemoryUsed) GetAllocatorBytesInUse() int64 {
	if m != nil {
		return m.AllocatorBytesInUse
	}
	return 0
}

// Output sizes recorded for a single execution of a graph node.
type NodeOutput struct {
	Slot              int32              `protobuf:"varint,1,opt,name=slot" json:"slot,omitempty"`
	TensorDescription *TensorDescription `protobuf:"bytes,3,opt,name=tensor_description,json=tensorDescription" json:"tensor_description,omitempty"`
}

func (m *NodeOutput) Reset()                    { *m = NodeOutput{} }
func (m *NodeOutput) String() string            { return proto.CompactTextString(m) }
func (*NodeOutput) ProtoMessage()               {}
func (*NodeOutput) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{1} }

func (m *NodeOutput) GetSlot() int32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *NodeOutput) GetTensorDescription() *TensorDescription {
	if m != nil {
		return m.TensorDescription
	}
	return nil
}

// For memory tracking.
type MemoryStats struct {
	HostTempMemorySize             int64   `protobuf:"varint,1,opt,name=host_temp_memory_size,json=hostTempMemorySize" json:"host_temp_memory_size,omitempty"`
	DeviceTempMemorySize           int64   `protobuf:"varint,2,opt,name=device_temp_memory_size,json=deviceTempMemorySize" json:"device_temp_memory_size,omitempty"`
	HostPersistentMemorySize       int64   `protobuf:"varint,3,opt,name=host_persistent_memory_size,json=hostPersistentMemorySize" json:"host_persistent_memory_size,omitempty"`
	DevicePersistentMemorySize     int64   `protobuf:"varint,4,opt,name=device_persistent_memory_size,json=devicePersistentMemorySize" json:"device_persistent_memory_size,omitempty"`
	HostPersistentTensorAllocIds   []int64 `protobuf:"varint,5,rep,packed,name=host_persistent_tensor_alloc_ids,json=hostPersistentTensorAllocIds" json:"host_persistent_tensor_alloc_ids,omitempty"`
	DevicePersistentTensorAllocIds []int64 `protobuf:"varint,6,rep,packed,name=device_persistent_tensor_alloc_ids,json=devicePersistentTensorAllocIds" json:"device_persistent_tensor_alloc_ids,omitempty"`
}

func (m *MemoryStats) Reset()                    { *m = MemoryStats{} }
func (m *MemoryStats) String() string            { return proto.CompactTextString(m) }
func (*MemoryStats) ProtoMessage()               {}
func (*MemoryStats) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{2} }

func (m *MemoryStats) GetHostTempMemorySize() int64 {
	if m != nil {
		return m.HostTempMemorySize
	}
	return 0
}

func (m *MemoryStats) GetDeviceTempMemorySize() int64 {
	if m != nil {
		return m.DeviceTempMemorySize
	}
	return 0
}

func (m *MemoryStats) GetHostPersistentMemorySize() int64 {
	if m != nil {
		return m.HostPersistentMemorySize
	}
	return 0
}

func (m *MemoryStats) GetDevicePersistentMemorySize() int64 {
	if m != nil {
		return m.DevicePersistentMemorySize
	}
	return 0
}

func (m *MemoryStats) GetHostPersistentTensorAllocIds() []int64 {
	if m != nil {
		return m.HostPersistentTensorAllocIds
	}
	return nil
}

func (m *MemoryStats) GetDevicePersistentTensorAllocIds() []int64 {
	if m != nil {
		return m.DevicePersistentTensorAllocIds
	}
	return nil
}

// Time/size stats recorded for a single execution of a graph node.
type NodeExecStats struct {
	// TODO(tucker): Use some more compact form of node identity than
	// the full string name.  Either all processes should agree on a
	// global id (cost_id?) for each node, or we should use a hash of
	// the name.
	NodeName         string                   `protobuf:"bytes,1,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	AllStartMicros   int64                    `protobuf:"varint,2,opt,name=all_start_micros,json=allStartMicros" json:"all_start_micros,omitempty"`
	OpStartRelMicros int64                    `protobuf:"varint,3,opt,name=op_start_rel_micros,json=opStartRelMicros" json:"op_start_rel_micros,omitempty"`
	OpEndRelMicros   int64                    `protobuf:"varint,4,opt,name=op_end_rel_micros,json=opEndRelMicros" json:"op_end_rel_micros,omitempty"`
	AllEndRelMicros  int64                    `protobuf:"varint,5,opt,name=all_end_rel_micros,json=allEndRelMicros" json:"all_end_rel_micros,omitempty"`
	Memory           []*AllocatorMemoryUsed   `protobuf:"bytes,6,rep,name=memory" json:"memory,omitempty"`
	Output           []*NodeOutput            `protobuf:"bytes,7,rep,name=output" json:"output,omitempty"`
	TimelineLabel    string                   `protobuf:"bytes,8,opt,name=timeline_label,json=timelineLabel" json:"timeline_label,omitempty"`
	ScheduledMicros  int64                    `protobuf:"varint,9,opt,name=scheduled_micros,json=scheduledMicros" json:"scheduled_micros,omitempty"`
	ThreadId         uint32                   `protobuf:"varint,10,opt,name=thread_id,json=threadId" json:"thread_id,omitempty"`
	ReferencedTensor []*AllocationDescription `protobuf:"bytes,11,rep,name=referenced_tensor,json=referencedTensor" json:"referenced_tensor,omitempty"`
	MemoryStats      *MemoryStats             `protobuf:"bytes,12,opt,name=memory_stats,json=memoryStats" json:"memory_stats,omitempty"`
}

func (m *NodeExecStats) Reset()                    { *m = NodeExecStats{} }
func (m *NodeExecStats) String() string            { return proto.CompactTextString(m) }
func (*NodeExecStats) ProtoMessage()               {}
func (*NodeExecStats) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{3} }

func (m *NodeExecStats) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeExecStats) GetAllStartMicros() int64 {
	if m != nil {
		return m.AllStartMicros
	}
	return 0
}

func (m *NodeExecStats) GetOpStartRelMicros() int64 {
	if m != nil {
		return m.OpStartRelMicros
	}
	return 0
}

func (m *NodeExecStats) GetOpEndRelMicros() int64 {
	if m != nil {
		return m.OpEndRelMicros
	}
	return 0
}

func (m *NodeExecStats) GetAllEndRelMicros() int64 {
	if m != nil {
		return m.AllEndRelMicros
	}
	return 0
}

func (m *NodeExecStats) GetMemory() []*AllocatorMemoryUsed {
	if m != nil {
		return m.Memory
	}
	return nil
}

func (m *NodeExecStats) GetOutput() []*NodeOutput {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *NodeExecStats) GetTimelineLabel() string {
	if m != nil {
		return m.TimelineLabel
	}
	return ""
}

func (m *NodeExecStats) GetScheduledMicros() int64 {
	if m != nil {
		return m.ScheduledMicros
	}
	return 0
}

func (m *NodeExecStats) GetThreadId() uint32 {
	if m != nil {
		return m.ThreadId
	}
	return 0
}

func (m *NodeExecStats) GetReferencedTensor() []*AllocationDescription {
	if m != nil {
		return m.ReferencedTensor
	}
	return nil
}

func (m *NodeExecStats) GetMemoryStats() *MemoryStats {
	if m != nil {
		return m.MemoryStats
	}
	return nil
}

type DeviceStepStats struct {
	Device    string           `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
	NodeStats []*NodeExecStats `protobuf:"bytes,2,rep,name=node_stats,json=nodeStats" json:"node_stats,omitempty"`
}

func (m *DeviceStepStats) Reset()                    { *m = DeviceStepStats{} }
func (m *DeviceStepStats) String() string            { return proto.CompactTextString(m) }
func (*DeviceStepStats) ProtoMessage()               {}
func (*DeviceStepStats) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{4} }

func (m *DeviceStepStats) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *DeviceStepStats) GetNodeStats() []*NodeExecStats {
	if m != nil {
		return m.NodeStats
	}
	return nil
}

type StepStats struct {
	DevStats []*DeviceStepStats `protobuf:"bytes,1,rep,name=dev_stats,json=devStats" json:"dev_stats,omitempty"`
}

func (m *StepStats) Reset()                    { *m = StepStats{} }
func (m *StepStats) String() string            { return proto.CompactTextString(m) }
func (*StepStats) ProtoMessage()               {}
func (*StepStats) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{5} }

func (m *StepStats) GetDevStats() []*DeviceStepStats {
	if m != nil {
		return m.DevStats
	}
	return nil
}

func init() {
	proto.RegisterType((*AllocatorMemoryUsed)(nil), "tensorflow.AllocatorMemoryUsed")
	proto.RegisterType((*NodeOutput)(nil), "tensorflow.NodeOutput")
	proto.RegisterType((*MemoryStats)(nil), "tensorflow.MemoryStats")
	proto.RegisterType((*NodeExecStats)(nil), "tensorflow.NodeExecStats")
	proto.RegisterType((*DeviceStepStats)(nil), "tensorflow.DeviceStepStats")
	proto.RegisterType((*StepStats)(nil), "tensorflow.StepStats")
}

func init() { proto.RegisterFile("tensorflow/core/framework/step_stats.proto", fileDescriptor15) }

var fileDescriptor15 = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x6d, 0x4f, 0xdb, 0x30,
	0x10, 0x56, 0x28, 0x74, 0xed, 0x95, 0x97, 0x62, 0x36, 0xc8, 0xe8, 0x18, 0x5d, 0xa5, 0x49, 0x65,
	0xd3, 0xca, 0x06, 0xda, 0x86, 0x26, 0xed, 0x03, 0x08, 0x26, 0x31, 0x01, 0x43, 0x01, 0x3e, 0x47,
	0x21, 0x3e, 0x46, 0x84, 0x13, 0x47, 0xb6, 0x5b, 0x06, 0xff, 0x61, 0x3f, 0x6a, 0xff, 0x60, 0x3f,
	0x67, 0x1f, 0x27, 0xdb, 0x69, 0x92, 0xb6, 0xf0, 0xcd, 0x79, 0xee, 0xb9, 0xf3, 0x93, 0xbb, 0xe7,
	0x0c, 0x6f, 0x14, 0x26, 0x92, 0x8b, 0x2b, 0xc6, 0x6f, 0x37, 0x43, 0x2e, 0x70, 0xf3, 0x4a, 0x04,
	0x31, 0xde, 0x72, 0x71, 0xb3, 0x29, 0x15, 0xa6, 0xbe, 0x54, 0x81, 0x92, 0xbd, 0x54, 0x70, 0xc5,
	0x09, 0x14, 0xdc, 0xd5, 0x4f, 0x8f, 0xe7, 0x05, 0x8c, 0xf1, 0x30, 0x50, 0x11, 0x4f, 0x7c, 0x8a,
	0x32, 0x14, 0x51, 0xaa, 0xcf, 0xb6, 0xc6, 0xea, 0xd6, 0xe3, 0x79, 0x36, 0x32, 0x99, 0xd3, 0xf9,
	0xeb, 0xc0, 0xd2, 0xae, 0x2d, 0xca, 0xc5, 0x31, 0xc6, 0x5c, 0xdc, 0x5d, 0x48, 0xa4, 0xe4, 0x35,
	0xcc, 0x07, 0x43, 0xd8, 0x4f, 0x82, 0x18, 0x5d, 0xa7, 0xed, 0x74, 0xeb, 0xde, 0x5c, 0x8e, 0x9e,
	0x04, 0x31, 0x92, 0x75, 0x68, 0x28, 0xae, 0x02, 0xe6, 0x5f, 0xde, 0x29, 0x94, 0xee, 0x54, 0xdb,
	0xe9, 0x56, 0x3c, 0x30, 0xd0, 0x9e, 0x46, 0xc8, 0x1a, 0x40, 0x8a, 0xc1, 0x4d, 0x16, 0xaf, 0x98,
	0x78, 0x5d, 0x23, 0x79, 0x98, 0x45, 0x03, 0xcc, 0xc2, 0xd3, 0x36, 0xac, 0x11, 0x1b, 0xde, 0x86,
	0xe5, 0x42, 0x85, 0xe1, 0xf8, 0x51, 0xe2, 0xf7, 0x25, 0xba, 0x33, 0x86, 0xba, 0x94, 0x47, 0x0d,
	0xff, 0x30, 0xb9, 0x90, 0xd8, 0x49, 0x00, 0x4e, 0x38, 0xc5, 0x1f, 0x7d, 0x95, 0xf6, 0x15, 0x21,
	0x30, 0x2d, 0x19, 0x57, 0x46, 0xfe, 0x8c, 0x67, 0xce, 0xe4, 0x08, 0xc8, 0x64, 0x43, 0x8c, 0xb8,
	0xc6, 0xd6, 0x5a, 0xaf, 0xe8, 0x62, 0xef, 0xdc, 0x1c, 0xf7, 0x0b, 0x92, 0xb7, 0xa8, 0xc6, 0xa1,
	0xce, 0xef, 0x0a, 0x34, 0x6c, 0xe7, 0xce, 0xf4, 0x40, 0xc9, 0x07, 0x78, 0x76, 0xcd, 0xa5, 0xf2,
	0x15, 0xc6, 0xa9, 0x1f, 0x9b, 0x80, 0x2f, 0xa3, 0x7b, 0xdb, 0xc1, 0x8a, 0x47, 0x74, 0xf0, 0x1c,
	0xe3, 0x34, 0xcb, 0x89, 0xee, 0x91, 0x7c, 0x84, 0x15, 0x8a, 0x83, 0x28, 0xc4, 0xc9, 0x24, 0xdb,
	0xd2, 0xa7, 0x36, 0x3c, 0x96, 0xf6, 0x15, 0x5a, 0xe6, 0xa6, 0x14, 0x85, 0x8c, 0xa4, 0xc2, 0x44,
	0x8d, 0xa4, 0xda, 0x6e, 0xbb, 0x9a, 0x72, 0x9a, 0x33, 0x4a, 0xe9, 0xbb, 0xb0, 0x96, 0xdd, 0xfa,
	0x48, 0x01, 0x3b, 0x8f, 0x55, 0x4b, 0x7a, 0xb0, 0xc4, 0x37, 0x68, 0x8f, 0x2b, 0xc8, 0x3a, 0x6b,
	0x26, 0xe3, 0x47, 0x54, 0xba, 0x33, 0xed, 0x4a, 0xb7, 0xe2, 0xbd, 0x18, 0x95, 0x61, 0x3b, 0x6b,
	0x9c, 0x77, 0x48, 0x25, 0xf9, 0x0e, 0x9d, 0x49, 0x29, 0x13, 0x95, 0xaa, 0xa6, 0xd2, 0xcb, 0x71,
	0x3d, 0xa3, 0xb5, 0x3a, 0x7f, 0xa6, 0x61, 0x4e, 0x1b, 0xe0, 0xe0, 0x17, 0x86, 0x76, 0x22, 0x2d,
	0xa8, 0x27, 0x9c, 0x62, 0xd9, 0xc7, 0x35, 0x0d, 0x18, 0x0b, 0x77, 0xa1, 0x19, 0x30, 0xa6, 0x97,
	0x51, 0x28, 0x3f, 0x8e, 0x42, 0xc1, 0x87, 0x3e, 0xd6, 0x1b, 0x70, 0xa6, 0xe1, 0x63, 0x83, 0x92,
	0x77, 0xb0, 0xc4, 0xd3, 0x8c, 0x28, 0x90, 0x0d, 0xc9, 0xb6, 0xcd, 0x4d, 0x9e, 0x1a, 0xae, 0x87,
	0x2c, 0xa3, 0x6f, 0xc0, 0x22, 0x4f, 0x7d, 0x4c, 0x68, 0x99, 0x6c, 0x5b, 0x3a, 0xcf, 0xd3, 0x83,
	0x84, 0x16, 0xd4, 0xb7, 0x40, 0xb4, 0x86, 0x31, 0xae, 0xf5, 0xf8, 0x42, 0xc0, 0xd8, 0x08, 0xf9,
	0x33, 0x54, 0xed, 0x90, 0x4c, 0x3f, 0x1a, 0x5b, 0xeb, 0x65, 0xc7, 0x3e, 0xb0, 0xcb, 0x5e, 0x46,
	0x27, 0x3d, 0xa8, 0x72, 0xb3, 0x14, 0xee, 0x13, 0x93, 0xb8, 0x5c, 0x4e, 0x2c, 0x56, 0xc6, 0xcb,
	0x58, 0xfa, 0x0d, 0x50, 0x51, 0x8c, 0x2c, 0x4a, 0xd0, 0x67, 0xc1, 0x25, 0x32, 0xb7, 0x66, 0xdf,
	0x80, 0x21, 0x7a, 0xa4, 0x41, 0xb2, 0x01, 0x4d, 0x19, 0x5e, 0x23, 0xed, 0x33, 0xa4, 0x43, 0xe9,
	0x75, 0x2b, 0x3d, 0xc7, 0x33, 0xe9, 0x2d, 0xa8, 0xab, 0x6b, 0x81, 0x01, 0xf5, 0x23, 0xea, 0x42,
	0xdb, 0xe9, 0xce, 0x79, 0x35, 0x0b, 0x1c, 0x52, 0x72, 0x02, 0x8b, 0x02, 0xaf, 0x50, 0x60, 0x12,
	0x22, 0xcd, 0x86, 0xef, 0x36, 0x8c, 0xd2, 0x57, 0x0f, 0xfc, 0x62, 0xc4, 0x93, 0xf2, 0x62, 0x36,
	0x8b, 0x5c, 0xeb, 0x07, 0xf2, 0x05, 0x66, 0x87, 0x66, 0xd6, 0x2e, 0x70, 0x67, 0xcd, 0x7e, 0xaf,
	0x94, 0x4b, 0x95, 0xd6, 0xd6, 0x6b, 0xc4, 0xc5, 0x47, 0x27, 0x84, 0x85, 0x7d, 0xe3, 0xb2, 0x33,
	0x85, 0xa9, 0x35, 0xd1, 0x32, 0x54, 0xad, 0xf1, 0x32, 0x07, 0x65, 0x5f, 0x64, 0x07, 0xc0, 0x98,
	0xcb, 0x5e, 0x32, 0x65, 0xf4, 0x3e, 0x1f, 0xef, 0x6c, 0xee, 0x45, 0xcf, 0x38, 0xd1, 0x5e, 0x72,
	0x00, 0xf5, 0xa2, 0xfc, 0x0e, 0xd4, 0x29, 0x0e, 0xb2, 0x2a, 0x8e, 0xa9, 0xd2, 0x2a, 0x57, 0x19,
	0x93, 0xe3, 0xd5, 0x28, 0x0e, 0xcc, 0x69, 0xef, 0x3d, 0xb8, 0x5c, 0xfc, 0x2c, 0x73, 0xf3, 0x77,
	0x7f, 0x6f, 0x21, 0x4f, 0x38, 0xd5, 0xcf, 0xbd, 0x3c, 0x75, 0xfe, 0x39, 0xce, 0x65, 0xd5, 0xbc,
	0xfd, 0xdb, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x37, 0xd2, 0x95, 0xee, 0xa1, 0x06, 0x00, 0x00,
}
